In [85]:
vaues = input("enter the values:")

enter the values:1 2\n3 4\n5 6


In [86]:
vaues

'1 2\\n3 4\\n5 6'

In [87]:

lst = vaues.strip().split("\\n")

In [88]:
lst

['1 2', '3 4', '5 6']

In [92]:
for element in lst:
    x = element.strip().split(" ")
    lst1.append(x)
 

In [94]:
arr =np.array(lst1,dtype="int32")

In [96]:
arr.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [97]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [22]:
lst.reverse()

In [24]:
lst[::-1]

['-23', '-1', '7', '5', '4', '3']

In [36]:
def arrays(arr):
    # complete this function
    # use numpy.array
    return np.array(arr[::-1],dtype="float64")

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

23 12 23 21
[21. 23. 12. 23.]


In [37]:
arr = input("enter the values")

enter the values1 2 3 4 5 6 7 8 9


In [38]:
arr

'1 2 3 4 5 6 7 8 9'

In [39]:
lst =arr.strip().split()

In [40]:
lst

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [44]:
a =np.array(lst,dtype ="int32")

In [45]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])